baseURL = "http://example.org/"
languageCode = "en-us"
title = "Gustav Jansson"
theme = "expose"
# disqusshortname = "madesopage"

[Params]
DateFormat = "Monday, Jan 2, 2006 at 15:04"
latestpostcount = 1
latestdevlogcount = 3
posts_navigation = true
sharebuttons = true

[Params.social]
Twitter = "sirGustav"
Reddit = "sirGustav"
Linkedin = "gsmjansson"
Keybase = "madeso"
Github = "madeso"
Photos = "https://plus.google.com/photos/104914211472274668508/albums/5824570292610928049"
