baseURL = "https://i.madeso.me/"
languageCode = "en-us"
title = "Gustav Jansson"
theme = "expose"
pygmentsUseClasses=true
# disqusshortname = "madesopage"

[Params]
LongDateFormat = "Monday, 2 January 2006 at 15:04"
ShortDateFormat = "2 January 2006"
latestpostcount = 3
latestdevlogcount = 3
posts_navigation = true
sharebuttons = false
highlightjs = true
InfiniteScroll = false

[Params.social]
Twitter = "sirGustav"
Keybase = "madeso"
Github = "madeso"
