baseURL = "https://madeso.github.io/"
languageCode = "en-us"
title = "Gustav Jansson"
theme = "expose"
pygmentsUseClasses=true
# disqusshortname = "madesopage"

[Params]
LongDateFormat = "Monday, 2 January 2006 at 15:04"
ShortDateFormat = "2 January 2006"
latestpostcount = 3
latestdevlogcount = 3
posts_navigation = true
sharebuttons = false
highlightjs = true
InfiniteScroll = false


[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2


[Params.social]
Twitter = "sirGustav"
Keybase = "madeso"
Github = "madeso"
Mastodon = "https://mastodon.gamedev.place/@madeso"
Tumblr = "https://imadesome.tumblr.com/"
Cohost = "https://cohost.org/madeso"


[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^vim$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']


