baseURL = "http://example.org/"
languageCode = "en-us"
title = "Gustav Jansson"
theme = "expose"

[Params]
DateFormat = "Monday, Jan 2, 2006 at 15:04"
latestpostcount = 1
latestdevlogcount = 3
posts_navigation = true
sharebuttons = true
